'use client';
import React, { useState, useEffect, useRef, useCallback } from 'react';
import { 
  X, ChevronRight, ChevronLeft, Sparkles, Activity, MapPin, 
  ThermometerSnowflake, ShieldAlert, Languages, Zap, Pill, 
  HelpCircle, CheckCircle2, RotateCcw, Compass, ArrowRight, Eye,
  Layers, Stethoscope, Bed, Database, Cpu, Network, Settings,
  Radio, Lock, ExternalLink
} from 'lucide-react';

export const TOUR_STEPS = [
  // =========================================================================
  // 1. NATIONAL COMMAND CENTER & REAL-TIME TELEMETRY CORE
  // =========================================================================
  {
    id: 'kpi-metrics',
    targetSelector: '#tour-kpi-metrics',
    tab: 'overview',
    title: 'Resilience Telemetry & KPI Sentinel',
    badge: 'National Grid',
    badgeColor: 'bg-emerald-500/15 text-emerald-300 border-emerald-500/30',
    icon: Activity,
    preferredPlacement: 'bottom',
    description: 'Aggregates vital health metrics across 1,188 facilities in real time. Continuously monitors the 96.4% National Resilience Index, bed & oxygen capacity (281k/362k beds occupied), doctor & nurse duty rosters, and identifies facilities under 48-hour critical deficit.',
    tip: 'Click on the Bed Occupancy or Staff cards anytime to jump directly to clinical ward rosters.'
  },
  {
    id: 'alert-stream',
    targetSelector: '#tour-alert-stream',
    tab: 'overview',
    title: 'Early Warning Deficit & Incident Stream',
    badge: 'Predictive Triage',
    badgeColor: 'bg-rose-500/15 text-rose-300 border-rose-500/30',
    icon: ShieldAlert,
    preferredPlacement: 'bottom',
    description: 'Continuously correlates monsoon precipitation, road cutoffs, and medicine burn rates. Color-coded triage flags stockouts (like Anti-Snake Venom) and allows immediate 1-click autonomous dispatch of surplus inventory from donor hospitals.',
    tip: 'Use the "Critical" filter to isolate clinics at highest risk of monsoon isolation.'
  },
  {
    id: 'action-center',
    targetSelector: '#tour-action-center',
    tab: 'overview',
    title: 'Prescriptive Immediate Action Queue',
    badge: 'Autonomous AI',
    badgeColor: 'bg-cyan-500/15 text-cyan-300 border-cyan-500/30',
    icon: Zap,
    preferredPlacement: 'left',
    description: 'AI-ranked priority tasks generated by the Autonomous Sentinel. Synthesizes cold-chain alerts, clinical bed pressures, and road flooding to present clear, executive next steps with instant dispatch triggers.',
    tip: 'One click executes pre-positioning routing from donor apex hospitals.'
  },
  {
    id: 'coldchain-card',
    targetSelector: '#tour-coldchain-card',
    tab: 'overview',
    title: 'Cold-Chain IoT Digital Watchdog',
    badge: 'Firebase RTDB',
    badgeColor: 'bg-indigo-500/15 text-indigo-300 border-indigo-500/30',
    icon: ThermometerSnowflake,
    preferredPlacement: 'left',
    description: 'Real-time telemetry from solar Ice-Lined Refrigerators (ILRs). Tracks temperature stability and Mean Kinetic Temperature (MKT) to protect heat-sensitive antivenoms and vaccines against power outages.',
    tip: 'Live green beacon indicates sub-second Firebase telemetry synchronization.'
  },

  // =========================================================================
  // 2. UNIFIED SIDEBAR DIRECTORY & ALL 12 OPERATIONAL MODULES
  // =========================================================================
  {
    id: 'sidebar-nav',
    targetSelector: '#tour-sidebar-nav',
    title: 'Unified Navigation & Operational Mesh',
    badge: '12 Health Subsystems',
    badgeColor: 'bg-purple-500/15 text-purple-300 border-purple-500/30',
    icon: Layers,
    preferredPlacement: 'right',
    description: 'Central nerve center connecting all 12 operational health sub-systems divided into Core Operations, Predictive Intelligence, Frontline Diagnostics, and System Governance.',
    tip: 'Sidebar collapses to maximize workspace on smaller screens or dense map views.'
  },
  {
    id: 'nav-overview',
    targetSelector: '#tour-nav-overview',
    tab: 'overview',
    title: 'Module 01: National Command Center',
    badge: 'Core Operations',
    badgeColor: 'bg-cyan-500/15 text-cyan-300 border-cyan-500/30',
    icon: Activity,
    preferredPlacement: 'right',
    description: 'Executive national overview synthesizing bed occupancy, healthcare worker rosters, live stockout triage feeds, and emergency rebalancing dispatches across India.',
    tip: 'Serves as the primary operational homepage for state health directors.'
  },
  {
    id: 'nav-clinical',
    targetSelector: '#tour-nav-clinical',
    tab: 'clinical',
    title: 'Module 02: Clinical Capacity & Staff Rosters',
    badge: 'Core Operations',
    badgeColor: 'bg-emerald-500/15 text-emerald-300 border-emerald-500/30',
    icon: Bed,
    preferredPlacement: 'right',
    description: 'Ward-level clinical monitoring tracking Primary Health Centre bed availability, oxygen manifold capacity, ICU ventilators, doctor/nurse shift attendance, and daily patient footfall.',
    tip: 'Identifies ward overcrowding and staff shortages in real time before patient care is compromised.'
  },
  {
    id: 'nav-map',
    targetSelector: '#tour-nav-map',
    tab: 'map',
    title: 'Module 03: Geospatial Rebalancer (GIS)',
    badge: 'Core Operations',
    badgeColor: 'bg-indigo-500/15 text-indigo-300 border-indigo-500/30',
    icon: MapPin,
    preferredPlacement: 'right',
    description: 'Full interactive Leaflet GIS displaying 1,188 health nodes across India, IMD flood inundation zones, drone air corridors, and autonomous electric delivery van routing around washed-out bridges.',
    tip: 'Click any facility marker to inspect live stock and dispatch emergency supplies.'
  },
  {
    id: 'nav-inventory',
    targetSelector: '#tour-nav-inventory',
    tab: 'inventory',
    title: 'Module 04: e-Aushadhi National Medicine Ledger',
    badge: 'Core Operations',
    badgeColor: 'bg-blue-500/15 text-blue-300 border-blue-500/30',
    icon: Pill,
    preferredPlacement: 'right',
    description: 'Unified pharmaceutical ledger tracking essential antivenoms, antibiotics, and fluids across rural clinics. Tracks lot numbers, batch expiries, current burn rates, and automated restock triggers.',
    tip: 'Fully aligned with Government of India e-Aushadhi health data standards.'
  },
  {
    id: 'nav-forecasting',
    targetSelector: '#tour-nav-forecasting',
    tab: 'forecasting',
    title: 'Module 05: Epidemic Outbreak Forecasting',
    badge: 'Predictive Intel',
    badgeColor: 'bg-rose-500/15 text-rose-300 border-rose-500/30',
    icon: ShieldAlert,
    preferredPlacement: 'right',
    description: 'Vertex AI and BigQuery machine learning models correlating seasonal monsoon precipitation (IMD) with IDSP disease morbidity to predict surges (Snakebite, Leptospirosis, Dengue) up to 30 days ahead.',
    tip: 'Triggers proactive stockpiling before seasonal floods cut off road connectivity.'
  },
  {
    id: 'nav-coldchain',
    targetSelector: '#tour-nav-coldchain',
    tab: 'coldchain',
    title: 'Module 06: Cold-Chain IoT Digital Twin',
    badge: 'Predictive Intel',
    badgeColor: 'bg-teal-500/15 text-teal-300 border-teal-500/30',
    icon: ThermometerSnowflake,
    preferredPlacement: 'right',
    description: 'Real-time telemetry and digital twin simulation for solar Ice-Lined Refrigerators (ILRs). Calculates Mean Kinetic Temperature (MKT) degradation curves, battery backup runtimes, and maintenance technician dispatches.',
    tip: 'MKT computation measures true cumulative potency degradation rather than just transient spikes.'
  },
  {
    id: 'nav-cloud-data',
    targetSelector: '#tour-nav-cloud-data',
    tab: 'cloud-data',
    title: 'Module 07: Google BigQuery & Firebase Cloud Hub',
    badge: 'Cloud & Big Data',
    badgeColor: 'bg-sky-500/15 text-sky-300 border-sky-500/30',
    icon: Database,
    preferredPlacement: 'right',
    description: 'Live interactive SQL analytics studio running over 10M+ national healthcare records with sub-second query latency, Firebase Realtime Database stream synchronization, and BigQuery partition monitoring.',
    tip: 'Run custom analytics queries over epidemiological trends and export datasets for research.'
  },
  {
    id: 'nav-federated',
    targetSelector: '#tour-nav-federated',
    tab: 'federated',
    title: 'Module 08: Federated Sovereign AI Mesh',
    badge: 'Privacy-Preserving AI',
    badgeColor: 'bg-purple-500/15 text-purple-300 border-purple-500/30',
    icon: Network,
    preferredPlacement: 'right',
    description: 'Multi-state and BRICS collaborative machine learning (DP-FedAvg). Trains outbreak prediction models collaboratively across sovereign state healthcare servers without ever sharing sensitive raw patient data (ε < 0.85).',
    tip: 'Maintains complete data sovereignty while sharing global predictive intelligence.'
  },
  {
    id: 'nav-simulation',
    targetSelector: '#tour-nav-simulation',
    tab: 'simulation',
    title: 'Module 09: Crisis Sandbox Drills',
    badge: 'Stress Testing',
    badgeColor: 'bg-amber-500/15 text-amber-300 border-amber-500/30',
    icon: Zap,
    preferredPlacement: 'right',
    description: 'Resilience drill simulator allowing disaster managers to model Category-4 cyclones, severe monsoon road cutoffs, and sudden 500% medicine demand surges to test supply chain response times before disasters strike.',
    tip: 'Identifies bottleneck routes and vulnerable health centres under simulated disaster stresses.'
  },
  {
    id: 'nav-vision',
    targetSelector: '#tour-nav-vision',
    tab: 'vision',
    title: 'Module 10: Gemini Vision Scanner',
    badge: 'Multimodal AI',
    badgeColor: 'bg-cyan-500/15 text-cyan-300 border-cyan-500/30',
    icon: Eye,
    preferredPlacement: 'right',
    description: 'Smartphone camera OCR powered by Gemini 2.0. Frontline ASHA workers snap photos of medicine blister packs and vials to instantly verify batch codes, extract expiry dates, and flag compromised packaging seals.',
    tip: 'Eliminates manual data entry errors and immediately detects damaged medicines.'
  },
  {
    id: 'nav-voice',
    targetSelector: '#tour-nav-voice',
    tab: 'voice',
    title: 'Module 11: ASHA Voice Copilot View',
    badge: '8 Indian Languages',
    badgeColor: 'bg-indigo-500/15 text-indigo-300 border-indigo-500/30',
    icon: Languages,
    preferredPlacement: 'right',
    description: 'Hands-free conversational assistant supporting Hindi, Telugu, Tamil, Marathi, Bengali, Kannada, Malayalam, and English for rural healthcare workers to check clinical protocols and request emergency supplies.',
    tip: 'Dedicated full-screen workspace with voice visualization, audio playback, and order tracking.'
  },
  {
    id: 'nav-settings',
    targetSelector: '#tour-nav-settings',
    tab: 'settings',
    title: 'Module 12: System Settings & Cloud Governance',
    badge: 'Governance & Security',
    badgeColor: 'bg-slate-500/15 text-slate-300 border-slate-500/30',
    icon: Settings,
    preferredPlacement: 'right',
    description: 'System configuration console for managing Google AI Studio Gemini API keys, inspecting real-time SSE stream status, verifying RBAC role permissions, and setting notification thresholds.',
    tip: 'Save your Gemini API key here to power all vision scanning and voice copilot features.'
  },

  // =========================================================================
  // 3. PERSISTENT COPILOT & HEADER TOOLS
  // =========================================================================
  {
    id: 'copilot-launcher',
    targetSelector: '#tour-copilot-launcher',
    title: 'Floating Multilingual Copilot Launcher',
    badge: 'Persistent Assistant',
    badgeColor: 'bg-indigo-500/15 text-indigo-300 border-indigo-500/30',
    icon: Languages,
    preferredPlacement: 'top',
    description: 'Always-accessible floating launcher available on every dashboard. Tap at any time to open the ASHA Voice Copilot without losing your current screen context, or press ⌘K.',
    tip: 'Supports both typing and spoken audio in 8 Indian regional languages.'
  },
  {
    id: 'header-controls',
    targetSelector: '#tour-header-controls',
    title: 'Architecture & Self-Guiding Tools',
    badge: 'System Reference',
    badgeColor: 'bg-amber-500/15 text-amber-300 border-amber-500/30',
    icon: Compass,
    preferredPlacement: 'bottom',
    description: 'Quick access to the 4-Step Crisis Pipeline, Glossary of healthcare terms, complete Google Cloud & Vertex AI Architecture diagrams, and this interactive tour whenever you need a refresher.',
    tip: 'Press the ? key anywhere in the application to instantly open the platform guide.'
  }
];

export default function AppTour({
  isOpen,
  onClose,
  activeTab,
  onNavigate
}) {
  const [currentStepIndex, setCurrentStepIndex] = useState(0);
  const [targetRect, setTargetRect] = useState(null);
  const [popoverPos, setPopoverPos] = useState({ top: 0, left: 0, placement: 'center' });
  const [isElementVisible, setIsElementVisible] = useState(false);
  const [windowDimensions, setWindowDimensions] = useState({ width: 1920, height: 1080 });

  const currentStep = TOUR_STEPS[currentStepIndex] || TOUR_STEPS[0];
  const popoverRef = useRef(null);
  const animationFrameRef = useRef(null);

  // Update window dimensions
  useEffect(() => {
    const updateDims = () => {
      setWindowDimensions({
        width: window.innerWidth,
        height: window.innerHeight
      });
    };
    updateDims();
    window.addEventListener('resize', updateDims);
    return () => window.removeEventListener('resize', updateDims);
  }, []);

  // Reset to step 0 and automatically return to Command Center ('overview') when starting tour
  useEffect(() => {
    if (isOpen) {
      setCurrentStepIndex(0);
      if (activeTab !== 'overview' && onNavigate) {
        onNavigate('overview');
      }
    }
  }, [isOpen]);

  // If a step targets an overview component and we are not on overview, switch to overview
  useEffect(() => {
    if (!isOpen || !currentStep) return;
    if (currentStep.tab === 'overview' && activeTab !== 'overview' && onNavigate) {
      onNavigate('overview');
    }
  }, [isOpen, currentStepIndex, currentStep, activeTab, onNavigate]);

  // Recalculate target element position & popover position
  const updatePosition = useCallback(() => {
    if (!isOpen || !currentStep) return false;

    const selector = currentStep.targetSelector;
    const element = selector ? document.querySelector(selector) : null;

    if (!element) {
      setIsElementVisible(false);
      setTargetRect(null);
      // Fallback: center in viewport until target mounts
      setPopoverPos({
        top: window.innerHeight / 2,
        left: window.innerWidth / 2,
        placement: 'center'
      });
      return false;
    }

    // If inside the sidebar, ensure sidebar container scrolls to it smoothly
    const sidebarNav = document.getElementById('tour-sidebar-nav');
    const headerEl = document.querySelector('header');
    const headerHeight = headerEl ? headerEl.offsetHeight : 68;
    const isHeaderElement = headerEl && headerEl.contains(element);

    if (sidebarNav && sidebarNav.contains(element)) {
      element.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
    } else if (!isHeaderElement) {
      const rect = element.getBoundingClientRect();
      const isObscuredByHeader = rect.top < headerHeight + 14;
      const isBelowFold = rect.bottom > window.innerHeight;

      if (isObscuredByHeader || isBelowFold) {
        const targetScrollY = window.scrollY + rect.top - headerHeight - 20;
        window.scrollTo({
          top: Math.max(0, targetScrollY),
          behavior: 'smooth'
        });
      }
    }

    const rect = element.getBoundingClientRect();

    // Check if element has dimension and is in DOM
    if (rect.width === 0 || rect.height === 0) {
      setIsElementVisible(false);
      setTargetRect(null);
      // Fallback: center in viewport
      setPopoverPos({
        top: window.innerHeight / 2,
        left: window.innerWidth / 2,
        placement: 'center'
      });
      return false;
    }

    const padding = 8;
    // Strict Header Boundary: Spotlight and cutout for page elements must NEVER overlap the sticky top header
    const minTop = isHeaderElement ? 0 : headerHeight + 4;
    const computedTarget = {
      top: Math.max(minTop, rect.top - padding),
      left: Math.max(0, rect.left - padding),
      width: rect.width + padding * 2,
      height: rect.height + padding * 2,
      bottom: rect.bottom + padding,
      right: rect.right + padding,
      centerX: rect.left + rect.width / 2,
      centerY: rect.top + rect.height / 2
    };

    setTargetRect(computedTarget);
    setIsElementVisible(true);

    // Compute optimal placement & coordinates for popover
    const popoverWidth = Math.min(420, window.innerWidth - 32);
    // Measure actual rendered height or safe estimate
    const measuredHeight = popoverRef.current ? popoverRef.current.offsetHeight : 360;
    const popoverHeight = Math.max(320, measuredHeight);
    const spacing = 16;

    const spaceAbove = computedTarget.top;
    const spaceBelow = window.innerHeight - computedTarget.bottom;
    const spaceLeft = computedTarget.left;
    const spaceRight = window.innerWidth - computedTarget.right;

    let chosenPlacement = currentStep.preferredPlacement || 'bottom';

    // Smart placement decision: Ensure enough clearance
    if (chosenPlacement === 'right' && spaceRight < popoverWidth + 24) {
      if (spaceBelow >= popoverHeight + 20) {
        chosenPlacement = 'bottom';
      } else if (spaceAbove >= popoverHeight + 20) {
        chosenPlacement = 'top';
      } else if (spaceLeft >= popoverWidth + 24) {
        chosenPlacement = 'left';
      }
    } else if (chosenPlacement === 'bottom' && spaceBelow < popoverHeight + 20) {
      if (spaceAbove >= popoverHeight + 20) {
        chosenPlacement = 'top';
      } else if (spaceRight >= popoverWidth + 24) {
        chosenPlacement = 'right';
      }
    } else if (chosenPlacement === 'top' && spaceAbove < popoverHeight + 20) {
      if (spaceBelow >= popoverHeight + 20) {
        chosenPlacement = 'bottom';
      } else if (spaceRight >= popoverWidth + 24) {
        chosenPlacement = 'right';
      }
    } else if (chosenPlacement === 'left' && spaceLeft < popoverWidth + 24) {
      if (spaceRight >= popoverWidth + 24) {
        chosenPlacement = 'right';
      } else if (spaceBelow >= popoverHeight + 20) {
        chosenPlacement = 'bottom';
      }
    }

    let top = 0;
    let left = 0;

    if (chosenPlacement === 'bottom') {
      top = computedTarget.bottom + spacing;
      left = computedTarget.centerX - popoverWidth / 2;
    } else if (chosenPlacement === 'top') {
      top = computedTarget.top - popoverHeight - spacing;
      left = computedTarget.centerX - popoverWidth / 2;
    } else if (chosenPlacement === 'right') {
      top = computedTarget.centerY - popoverHeight / 2;
      left = computedTarget.right + spacing;
    } else if (chosenPlacement === 'left') {
      top = computedTarget.centerY - popoverHeight / 2;
      left = computedTarget.left - popoverWidth - spacing;
    }

    // Strict Viewport Clamping (guarantee popover never overflows screen edges or bottom)
    const margin = 16;
    const maxLeft = window.innerWidth - popoverWidth - margin;
    const maxTop = window.innerHeight - popoverHeight - margin;

    left = Math.max(margin, Math.min(left, maxLeft));
    top = Math.max(margin, Math.min(top, maxTop));

    setPopoverPos({ top, left, placement: chosenPlacement });
    return true;
  }, [isOpen, currentStep]);

  // Keep position synchronized on scroll, resize, step change, and tab transitions
  useEffect(() => {
    if (!isOpen) return;

    // Active polling loop: checks every 60ms up to 40 times (~2.4s) until target mounts in DOM
    let attempts = 0;
    const maxAttempts = 40;
    const pollInterval = setInterval(() => {
      attempts++;
      const found = updatePosition();
      if (found || attempts >= maxAttempts) {
        clearInterval(pollInterval);
      }
    }, 60);

    // Initial immediate invocation
    updatePosition();

    const handleScrollOrResize = () => {
      if (animationFrameRef.current) cancelAnimationFrame(animationFrameRef.current);
      animationFrameRef.current = requestAnimationFrame(updatePosition);
    };

    window.addEventListener('resize', handleScrollOrResize);
    window.addEventListener('scroll', handleScrollOrResize, true);

    return () => {
      clearInterval(pollInterval);
      if (animationFrameRef.current) cancelAnimationFrame(animationFrameRef.current);
      window.removeEventListener('resize', handleScrollOrResize);
      window.removeEventListener('scroll', handleScrollOrResize, true);
    };
  }, [isOpen, currentStepIndex, activeTab, updatePosition]);

  // Keyboard navigation: Arrows & Escape
  useEffect(() => {
    if (!isOpen) return;

    const handleKeyDown = (e) => {
      if (e.key === 'Escape') {
        e.preventDefault();
        onClose();
      } else if (e.key === 'ArrowRight' || e.key === 'Enter') {
        e.preventDefault();
        handleNext();
      } else if (e.key === 'ArrowLeft') {
        e.preventDefault();
        handlePrev();
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  });

  const handleNext = () => {
    if (currentStepIndex < TOUR_STEPS.length - 1) {
      setCurrentStepIndex(prev => prev + 1);
    } else {
      handleComplete();
    }
  };

  const handlePrev = () => {
    if (currentStepIndex > 0) {
      setCurrentStepIndex(prev => prev - 1);
    }
  };

  const handleComplete = () => {
    try {
      localStorage.setItem('SANJEEVANI_TOUR_COMPLETED', 'true');
    } catch {
      // ignore
    }
    onClose();
  };

  if (!isOpen) return null;

  const StepIcon = currentStep.icon || Sparkles;
  const isFirstStep = currentStepIndex === 0;
  const isLastStep = currentStepIndex === TOUR_STEPS.length - 1;
  const progressPct = Math.round(((currentStepIndex + 1) / TOUR_STEPS.length) * 100);

  return (
    <>
      {/* 
        ========================================================================
        LAYER 1: SVG CUTOUT MASK BACKDROP (z-index: 9990)
        Covers the entire screen, with a clean rounded-rect hole directly over
        the highlighted component, avoiding stacking context conflicts.
        ========================================================================
      */}
      <svg
        className="fixed inset-0 w-full h-full pointer-events-auto transition-all duration-300"
        style={{ zIndex: 9990 }}
      >
        <defs>
          <mask id="tour-cutout-mask" x="0" y="0" width="100%" height="100%">
            {/* White covers entire screen (opaque) */}
            <rect x="0" y="0" width="100%" height="100%" fill="white" />
            {/* Black cutout creates a transparent window over target */}
            {isElementVisible && targetRect && (
              <rect
                x={targetRect.left}
                y={targetRect.top}
                width={targetRect.width}
                height={targetRect.height}
                rx="14"
                ry="14"
                fill="black"
              />
            )}
          </mask>
        </defs>

        {/* Dark backdrop rect with mask applied */}
        <rect
          x="0"
          y="0"
          width="100%"
          height="100%"
          fill="#030712"
          fillOpacity="0.82"
          mask="url(#tour-cutout-mask)"
          onClick={onClose}
          className="cursor-pointer"
        />
      </svg>

      {/* 
        ========================================================================
        LAYER 2: HIGHLIGHT SPOTLIGHT FRAME (z-index: 9995)
        Glowing, animated border framing the active element.
        ========================================================================
      */}
      {isElementVisible && targetRect && (
        <div
          className="fixed pointer-events-none transition-all duration-300 ease-out"
          style={{
            zIndex: 9995,
            top: targetRect.top,
            left: targetRect.left,
            width: targetRect.width,
            height: targetRect.height,
            borderRadius: '14px',
            border: '2px solid rgba(6, 182, 212, 0.9)',
            boxShadow: '0 0 25px rgba(6, 182, 212, 0.45), inset 0 0 15px rgba(6, 182, 212, 0.2)'
          }}
        >
          {/* Animated beacon ring */}
          <span className="absolute -inset-1 rounded-2xl border border-cyan-400/40 animate-ping opacity-30" />
        </div>
      )}

      {/* 
        ========================================================================
        LAYER 3: TOUR POPOVER CARD (z-index: 9999)
        Clean modern glassmorphism dialog with 100% solid, non-transparent 
        background, zero bleed-through, strict boundary clamping, & arrow.
        ========================================================================
      */}
      <div
        ref={popoverRef}
        className="fixed transition-all duration-200 ease-out animate-copilot-pop"
        style={{
          zIndex: 9999,
          ...(popoverPos.placement === 'center'
            ? {
                top: '50%',
                left: '50%',
                transform: 'translate(-50%, -50%)',
                width: 'min(92vw, 420px)'
              }
            : {
                top: `${popoverPos.top}px`,
                left: `${popoverPos.left}px`,
                width: 'min(92vw, 420px)'
              })
        }}
      >
        <div 
          className="rounded-2xl p-5 text-slate-100 space-y-4 relative border border-cyan-500/50"
          style={{
            backgroundColor: '#090d16',
            boxShadow: '0 25px 60px -10px rgba(0, 0, 0, 0.95), 0 0 35px rgba(6, 182, 212, 0.25)'
          }}
        >
          {/* Directional Arrow pointing towards target element */}
          {isElementVisible && popoverPos.placement !== 'center' && (
            <div
              className={`absolute w-3 h-3 rotate-45 border border-cyan-500/50 ${
                popoverPos.placement === 'bottom'
                  ? '-top-1.5 left-8 border-b-0 border-r-0'
                  : popoverPos.placement === 'top'
                  ? '-bottom-1.5 left-8 border-t-0 border-l-0'
                  : popoverPos.placement === 'right'
                  ? '-left-1.5 top-8 border-t-0 border-r-0'
                  : '-right-1.5 top-8 border-b-0 border-l-0'
              }`}
              style={{ backgroundColor: '#090d16' }}
            />
          )}

          {/* Top Bar: Icon, Step Counter, Badge & Close */}
          <div className="flex items-center justify-between gap-2 pb-2.5 border-b border-slate-800">
            <div className="flex items-center gap-2.5">
              <div className="w-8 h-8 rounded-lg bg-gradient-to-tr from-cyan-500/20 to-indigo-500/20 border border-cyan-500/40 flex items-center justify-center text-cyan-400 shrink-0 shadow-sm">
                <StepIcon size={17} />
              </div>
              <div>
                <span className="text-[10px] font-mono uppercase tracking-wider text-slate-400 font-bold">
                  Step {currentStepIndex + 1} of {TOUR_STEPS.length}
                </span>
                <div className="flex items-center gap-1.5 mt-0.5">
                  <span className={`text-[9px] font-mono font-bold px-1.5 py-0.2 rounded border ${currentStep.badgeColor}`}>
                    {currentStep.badge}
                  </span>
                </div>
              </div>
            </div>

            <button
              onClick={onClose}
              className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
              title="Close Tour (Esc)"
              aria-label="Close Tour"
            >
              <X size={16} />
            </button>
          </div>

          {/* Step Progress Line */}
          <div className="w-full bg-slate-800 rounded-full h-1.5 overflow-hidden">
            <div 
              className="bg-gradient-to-r from-cyan-400 via-sky-400 to-indigo-500 h-full rounded-full transition-all duration-300"
              style={{ width: `${progressPct}%` }}
            />
          </div>

          {/* Title & Description */}
          <div className="space-y-2">
            <div className="flex items-center justify-between gap-2">
              <h3 className="text-base font-bold text-white tracking-tight font-display">
                {currentStep.title}
              </h3>
              {/* Optional Launch Dashboard button if step refers to another tab */}
              {currentStep.tab && currentStep.tab !== activeTab && onNavigate && (
                <button
                  onClick={() => onNavigate(currentStep.tab)}
                  className="shrink-0 text-[10px] font-semibold text-cyan-300 hover:text-white flex items-center gap-1 px-2 py-0.5 rounded-lg bg-cyan-500/10 border border-cyan-500/30 hover:bg-cyan-500/20 transition-all"
                  title="Switch to this module's dashboard"
                >
                  <span>Open</span>
                  <ExternalLink size={10} />
                </button>
              )}
            </div>
            <p className="text-xs text-slate-300 leading-relaxed">
              {currentStep.description}
            </p>
          </div>

          {/* Actionable Tip Box */}
          {currentStep.tip && (
            <div className="bg-slate-950/80 border border-cyan-500/25 rounded-xl p-2.5 flex items-start gap-2 text-[11px] text-cyan-300 leading-snug">
              <Sparkles size={14} className="text-cyan-400 shrink-0 mt-0.5" />
              <span>{currentStep.tip}</span>
            </div>
          )}

          {/* Footer Controls: Skip, Back, Next / Finish */}
          <div className="pt-2 flex items-center justify-between gap-2 border-t border-slate-800">
            <button
              onClick={onClose}
              className="text-xs text-slate-400 hover:text-slate-200 px-2 py-1 transition-colors"
            >
              Skip Tour
            </button>

            <div className="flex items-center gap-2">
              {!isFirstStep && (
                <button
                  onClick={handlePrev}
                  className="btn-secondary text-xs px-3 py-1.5 font-semibold flex items-center gap-1"
                >
                  <ChevronLeft size={14} />
                  <span>Back</span>
                </button>
              )}

              <button
                onClick={handleNext}
                className="btn-primary text-xs px-4 py-1.5 font-bold flex items-center gap-1 shadow-lg shadow-cyan-500/25"
              >
                <span>{isLastStep ? 'Finish Tour' : 'Next'}</span>
                {!isLastStep ? <ChevronRight size={14} /> : <CheckCircle2 size={14} />}
              </button>
            </div>
          </div>

          {/* Keyboard navigation hint */}
          <div className="flex items-center justify-between text-[10px] font-mono text-slate-500 pt-0.5">
            <span>← / → Navigate</span>
            <span>Esc Exit</span>
          </div>

        </div>
      </div>
    </>
  );
}
