from fastapi import APIRouter, Query
from typing import Optional
from ..services.forecasting import get_outbreak_predictions
from ..utils.response_helper import paginated_response, success_response

router = APIRouter(tags=["Predictive Outbreak & Stockout Engine"])


@router.get("/api/forecasting/outbreak-risk")
@router.get("/api/forecasting/outbreaks")
@router.get("/api/forecasting/predict")
def fetch_outbreak_predictions(
    page: int = Query(1, ge=1, description="Page number"),
    page_size: int = Query(20, ge=1, le=5000, description="Records per page"),
    state: Optional[str] = Query(None, description="Filter by state"),
    district: Optional[str] = Query(None, description="Filter by district"),
    facility_id: Optional[str] = Query(None, description="Filter by specific facility ID")
):
    raw_forecast = get_outbreak_predictions()
    forecasts = raw_forecast.get("facility_forecasts", [])

    if state:
        forecasts = [f for f in forecasts if state.lower() in f.get("state", "").lower()]
    if district:
        forecasts = [f for f in forecasts if district.lower() in f.get("district", "").lower()]
    if facility_id:
        forecasts = [f for f in forecasts if facility_id.lower() in f.get("facility_id", "").lower()]

    return paginated_response(
        items=forecasts,
        page=page,
        page_size=page_size,
        message="Epidemiological surge forecasts generated by Google Gemini AI",
        metadata={
            "model_framework": raw_forecast.get("model_framework"),
            "confidence_interval": raw_forecast.get("confidence_interval"),
            "forecast_horizon": raw_forecast.get("forecast_horizon"),
            "critical_alerts_count": raw_forecast.get("critical_alerts_count", 0),
            "high_risk_alerts": raw_forecast.get("high_risk_alerts", [])[:5]
        }
    )
